# Generated by Django 5.1.5 on 2025-01-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artysci',
            fields=[
                ('id_artysty', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('rok_urodzenia', models.DateField()),
                ('rok_smierci', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eksponaty',
            fields=[
                ('id_eksponatu', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('wysokosc', models.IntegerField()),
                ('szerokosc', models.IntegerField()),
                ('waga', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('czy_cenny', models.BooleanField(default=False)),
                ('id_artysty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.artysci')),
            ],
        ),
    ]
