# Generated by Django 5.1.5 on 2025-01-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_gallery_renter_exhibition_rented_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='id_renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.renter'),
        ),
    ]
